# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lucio's Blog
email: martinezlucio.com@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about software by Lucio Martinez.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://luciomartinez.github.io"
twitter_username: delucioux
github_username:  luciomartinez

# Build settings
markdown: kramdown
